### ISSUE TITLE
FATAL_ERROR: Parse error in the keymap file line 125: bad key sequence

### ISSUE THREAD

**Issue by alan12345678** [jonsafari/mocp#10]
What I've done is this:

opened the example config file located in ~/.moc and read it. Set about editing accordingly and after tweaking a few basic settings all well, mocp launches and plays successfully.

I have a UK keyboard (en_GB.UTF8) so, understanding the rationale behind the fast directory shortcuts, set about changing the few that differ from a US key layout - namely the positions of the "£", "$" and "@" keys.

After editing just the first one at <Shift+3>, loading mocp from a terminal gives:

FATAL_ERROR: Parse error in the keymap file line 125: bad key sequence

Line 125 is the line containing:

`go_to_fast_dir3       = £` 

If I simply remove the £ character and replace it with  @ it runs fine, so it's this character causing my problem. I DO hope this supports keyboard languages ;)

p.s. also note that as part of testing, I simply loaded directly the default keyboard map. That told me that `"` has been assigned twice - once as `go_to_fast_dir2` and again at `mark_end`. I commented out the second entry.

**Comment by tomaszg7** [comment]
You might want to report it on MOC webpage instead of random github repository. 

There are some related issues already reported there:
http://moc.daper.net/node/1561
http://moc.daper.net/node/341
http://moc.daper.net/node/676

**Comment by alan12345678** [comment]
thank you. My apologies - this is where my search directed me, I should have looked more closely! Won't happen again :)

*alan ansell figurative painting
Itzac
France*

**We are what we repeatedly do. Excellence is therefore not an act but a habit.
 Aristotle**




----- Original message -----
