### ISSUE TITLE
No seeking in webm-files

### ISSUE THREAD

**Issue by suuuehgi** [jonsafari/mocp#15]
Hi,

there seems to be no seeking for / in opus / webm-files. Is there any hope that this is still to come? :-)
I currently have a opus-file with a bitrate just acceptable so that there is no real buffer for transcoding it to mp3. 

Cheers

**Comment by jarun** [comment]
I'm seeing this too!

**Comment by aantonssizov** [comment]
Same problem!

**Comment by tomaszg7** [comment]
You might want to report it to MOC developers on MOC webpage, not some random github clone.

**Comment by suuuehgi** [comment]
> You might want to report it to MOC developers on MOC webpage, not some random github clone.

You are right, I oversaw that. Apart from that, when I compile the current unstable 2.6-alpha3, it seeks as expected.
