### ISSUE TITLE
Keyboard shortcut not working

### ISSUE THREAD

**Issue by tifDev** [jonsafari/mocp#17]
My pc has the default key combination to play/pause media and next/previous media.

For example fn+home it's my default play/pause. I tried to assign this combination to mocp but it doesn't work. Then i tested with fn+p and it worked. Is it because it's a terminal app and the system doesn't recognize as "media" ? How can i fix this?

**Comment by tomaszg7** [comment]
http://moc.daper.net/node/1571
http://moc.daper.net/node/2526
http://moc.daper.net/node/1784
