### ISSUE TITLE
Official repo for mocp and support for TERM=konsole-256color

### ISSUE THREAD

**Issue by emugel** [jonsafari/mocp#2]
Hello there,
do you know if there's an official git for mocp?
Right now I can't define colors in themes with e.g. `colordef black = 700 600 600` but it does work with urxvt, so I thought I'd compile mocp and maybe try to fix it. If you have any info feel free to drop me a message :)

**Comment by emugel** [comment]
Also when running `autoconf` to generate the 'configure' file, I get this:

```
configure.in:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allo
      See the Autoconf documentation.
configure.in:34: error: possibly undefined macro: AC_LIBTOOL_DLOPEN
configure.in:35: error: possibly undefined macro: AC_DISABLE_STATIC
configure.in:36: error: possibly undefined macro: AC_ENABLE_SHARED
configure.in:37: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.in:38: error: possibly undefined macro: AC_LIB_LTDL
configure.in:40: error: possibly undefined macro: AC_SUBST
configure.in:49: error: possibly undefined macro: AC_DEFINE
configure.in:110: error: possibly undefined macro: AM_ICONV
configure.in:240: error: possibly undefined macro: AC_SEARCH_LIBS
configure:6087: error: possibly undefined macro: AM_CONDITIONAL
```

**Comment by jonsafari** [comment]
Hi,
Currently there is no official Git repo:  http://moc.daper.net/node/1520 .  I wish there were, so that I don't need to run clunky git-svn updates and merges.
You'll need to post bug reports to the (currently) official site at  http://moc.daper.net/forum/19 .
Good luck!

**Comment by emugel** [comment]
Ok thanks ;)
Btw I found how to generate the 'configure' file properly: had to run `autoreconf -if`, not autoconf.

**Comment by jonsafari** [comment]
Oh yes, I ran into that problem with autoreconf a while back too, and arrived at the same solution.
