### ISSUE TITLE
independent volume

### ISSUE THREAD

**Issue by grenzionky** [jonsafari/mocp#20]
up until today, the volume in mocp was not synced to my system volume so i was able to turn down mocp while keeping other system sounds loud, but now when i turn down mocp my system volume also goes down. 

how can i get back the old feature?

**Comment by grenzionky** [comment]
now changing the volume inside of mocp doesnt change the musics volume at all. not even if i set it to 0%… i didnt touch any settings

**Comment by silvus** [comment]
It may depend on your audio configuration (Alsa? Pulsaudio?).
Maybe look in pavucontrol or alsamixer?

Moc has a configuration option about the sound driver to use:
```
# Sound driver - OSS, ALSA, JACK, SNDIO (on OpenBSD) or null (only for
# debugging).  You can enter more than one driver as a colon-separated
# list.  The first working driver will be used.
#SoundDriver = JACK:ALSA:OSS
```

**Comment by grenzionky** [comment]
i use pulseaudio

**Comment by silvus** [comment]
Maybe check the applications sounds levels in pavucontrol:
![pavucontrol capture](https://user-images.githubusercontent.com/1922454/86328788-919d6c80-bc45-11ea-84fb-ec83c507889a.png)

**Comment by grenzionky** [comment]
only setting the SoundDriver to ALSA works, and then it links mocp with the system volume.

i *can* change mocp's volume manually in pavucontrol, but thats very annoying to do every time i want to change the volume a little… 

Is there any way to make mocp use pulseaudio, or is there any way to make mocp's volume independent from system volume within mocp?

**Comment by grenzionky** [comment]
i figured it out! you need to press `x` (or whatever `toggle_mixer` is bound to) till you reach the Soft mixer, then u can change the volume in mocp and it wont affect any other program

**Comment by silvus** [comment]
Glad you found!
There are mixer options (depending on the SoundDriver) but not sure if it helps:

```
# OSS output settings.
#OSSMixerChannel1 = pcm             # 'pcm', 'master' or 'speaker'
#OSSMixerChannel2 = master          # 'pcm', 'master' or 'speaker'

# ALSA output settings.
#ALSADevice = default
#ALSAMixer1 = PCM
#ALSAMixer2 = Master
```

Otherwise you should test with this option:

```
# Save software mixer state?
# If enabled, a file 'softmixer' will be created in '~/.moc/' storing the
# mixersetting set when the server is shut down.
# Note that there is a "hidden" 'Amplification' setting in that file.
# Amplification (0-200) is used to scale the mixer setting (0-100).  This
# results in a higher signal amplitude but may also produce clipping.
#Softmixer_SaveState = yes
```

**Comment by grenzionky** [comment]
Thanks for helping me out btw, its very much appreciated

> Glad you found!
> There are mixer options (depending on the SoundDriver) but not sure if it helps:
> 
> ```
> # OSS output settings.
> #OSSMixerChannel1 = pcm             # 'pcm', 'master' or 'speaker'
> #OSSMixerChannel2 = master          # 'pcm', 'master' or 'speaker'
> 
> # ALSA output settings.
> #ALSADevice = default
> #ALSAMixer1 = PCM
> #ALSAMixer2 = Master
> ```

this only changes the name of the speaker in the program



> Otherwise you should test with this option:
> 
> ```
> # Save software mixer state?
> # If enabled, a file 'softmixer' will be created in '~/.moc/' storing the
> # mixersetting set when the server is shut down.
> # Note that there is a "hidden" 'Amplification' setting in that file.
> # Amplification (0-200) is used to scale the mixer setting (0-100).  This
> # results in a higher signal amplitude but may also produce clipping.
> #Softmixer_SaveState = yes
> ```

this saves the volume to what it was last set to, which is pretty cool, but it doesnt set the default sound controls to "Soft" which is what i want. Its annoying to have to press `x` 2 times every time i open mocp in order to change the volume.

**Comment by silvus** [comment]
For what I understand of the source code of Moc and the research I have done, there is no simple solution...
I think the only way is by patching the source code (so you need to compile it): 

> I don't think there is a way short of modifying MOC source - you would only need to change the line:
> ```static int current_mixer = 0;```
> in audio.c to
> ```static int current_mixer = 2;```

[Source](https://moc.daper.net/node/1512)

Good luck!
