### ISSUE TITLE
What about using libyui? TUI+GUI support in one!

### ISSUE THREAD

**Issue by timofonic** [jonsafari/mocp#3]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by jonsafari** [comment]
Good idea!  I don't maintain the main project; I just add a few tweaks and documentation.  These kinds of requests should go to http://moc.daper.net/forum/22

**Comment by timofonic** [comment]
Hello.

@jonsafari Thanks. I wrote it here: http://moc.daper.net/node/1783

If you know of any project that might have some interest in the libyui as concept and possibilities, please mention it. I'm just a user, but I consider a more flexible approach than current ones.

Thanks in advance.

Kind regards.

**Comment by jonsafari** [comment]
Yes, it seems nice.  If/when I come across a suitable project, I'll keep it in mind.
