### ISSUE TITLE
Volume can not go over 100%

### ISSUE THREAD

**Issue by happydig** [jonsafari/mocp#8]
When volume on Ubuntu Desktop go over 100%,  moc server will exit.

The log is:
```
Running the server...
Trying ALSA...
mocp: alsa.c:319: alsa_read_mixer_raw: Assertion `RANGE(0, vol, 100)' failed.

FATAL_ERROR: Server exited!
```
Thanks.

**Comment by tomaszg7** [comment]
You should report these issues on MOC forum, this is only an unofficial mirror, which is not followed by MOC developers. The issue was already reported on MOC webpage, and you can follow it there:  http://moc.daper.net/node/1600

**Comment by mschilli87** [comment]
@tomaszg7: Maybe an issue template could be added to this repository to point people in the right direction in time?

**Comment by tomaszg7** [comment]
That's not up to me, I don't manage this repo. I only follow it to try and point people in the right direction ;)

**Comment by happydig** [comment]
This is screenshot from Ubuntu Desktop. 
![screenshot from 2019-01-18 21-01-56](https://user-images.githubusercontent.com/37877812/51388444-65cb1b80-1b64-11e9-9b10-7c8907b4e7c3.png)

With pactl command, you can set volume to 150%:
```
pactl set-sink-volume 0 150%
```

**Comment by happydig** [comment]
@tomaszg7  Because there is no volume issue with the official release from Ubuntu repository. I think this is the unique issue with this fork. Thanks.
