### ISSUE TITLE
Feature request: sorting files by date

### ISSUE THREAD

**Issue by axel22** [jonsafari/mocp#9]
Hi! Thanks for a great, CPU-friendly, and user friendly music player.

Please consider adding an option to sort the files by their date. This would be quite useful.

**Comment by tomaszg7** [comment]
Please consider submitting this request to MOC developers at http://moc.daper.net/. This is only an unofficial clone of the repository.

**Comment by mschilli87** [comment]
@axel22: If you do so, please also try to be more precise which date are you referring to? The file creation date? The file modification date? The release date from ID3 tags?

**Comment by axel22** [comment]
Thanks for the super-quick replies!

I created it (either creation or modification date would be fine for me, but the more the merrier).

http://moc.daper.net/node/2319

**Comment by mschilli87** [comment]
@axel22: Don't forget to close this issue. :wink:
